### ISSUE TITLE
Maybe you are opening a URL which is not git-push'ed yet. OK? が毎回表示される

### ISSUE THREAD

**Issue by take** [tyru/open-browser-github.vim#12]
private repoの場合どうやら https://github.com/tyru/open-browser-github.vim/blob/22f01413daec5cc03ac06c473c7caec31dce85cc/autoload/openbrowser/github.vim#L102 が毎回falseを返すようなのですが、このチェックを設定で外すようなことはできますでしょうか？＞＜

**Comment by tyru** [comment]
了解です。とりあえず無視する変数を追加します。しばらくお待ちください。

**Comment by tyru** [comment]
追加しました。.vimrcに次の設定を書いて試してみてください。
```viml
let g:openbrowser_github_url_exists_check = 'ignore'
```

**Comment by tyru** [comment]
すみません、`url_exists_check`ブランチにpushしたのでそっちを試してみてください。

**Comment by take** [comment]
@tyru ありがとうございます！！！！試してみましたところ想定通りの挙動を確認できました助かりますありがとうございます！ :bow:

**Comment by tyru** [comment]
いえいえ、どういたしまして。
