### ISSUE TITLE
Behaviors of :OpenGithubIssue and :OpenGithubPullReq with no arguments

### ISSUE THREAD

**Issue by tyru** [tyru/open-browser-github.vim#21]
To @rhysd (via #20)

すみません、よく見ずにマージしてしまって本当に悪いのですが、
すでに引数がない場合は別の挙動が割り当てられているのを失念していました…

これらの挙動に関しては、#20 で入れた対応は一旦 revert し、
別の Ex コマンド `:OpenGithubIssueOnCursor` と `:OpenGithubPullReqOnCursor` を追加する形で対応することを考えています。
これら2つの Ex コマンドに関してなるべく @rhysd さんの希望の挙動にしたいのですが、以下のような挙動で大丈夫でしょうか？

```viml
" 引数なしで呼び出すとカーソル下の issue 番号（#xxx）を開く
:OpenGithubIssueOnCursor
" これはエラー（引数は受け付けない）
:OpenGithubIssueOnCursor 123
```

引数を受け付けるかどうかなどについて @rhysd さんのニーズに合わせて変えていきたいです。

**Comment by rhysd** [comment]
あれ，引き数が与えられていない場合は issues のページ（e.g. https://github.com/tyru/open-browser-github.vim/issues ）を開くんじゃなかったでしたっけ？それがおっしゃっている「別の挙動」ということでよいでしょうか？

Revert 全然問題ないです．もし必要であれば僕の方でプルリク出し直しても OK です :+1:

**Comment by tyru** [comment]
> 引き数が与えられていない場合は issues のページ（e.g. https://github.com/tyru/open-browser-github.vim/issues ）を開く

はい。引数が与えられていない場合に

* カーソル下にチケット番号があったらそのチケット番号を開く
* カーソル下にチケット番号がなかったら issues のページを開く

と挙動が異なる場合があるのはユーザを混乱させてしまうかなと…（常に issues のページを開くようにしたい）

> Revert 全然問題ないです．もし必要であれば僕の方でプルリク出し直しても OK です

おお、助かります！
プルリクお願いします！

**Comment by tyru** [comment]
#22 で

> カーソル下の issue を開くためだけに新しいコマンドを入れるのも微妙かなぁと思ったのでとりあえず revert だけするプルリクです．これくらいなら .vimrc に設定書いて :OpenGithubIssue を呼べば良いかなということで，そうしたいと思います．

とのことですが、新機能入れないならこの issue も close しちゃいます？

**Comment by rhysd** [comment]
ですね．また何かあればプルリクします💪

**Comment by rhysd** [comment]
すみません，iPad で見ると Close ボタンが何故か無いので close お願いします…

**Comment by tyru** [comment]
ありがとうございました！
