### ISSUE TITLE
ブランチ名を元に該当するPull Requestを開く機能

### ISSUE THREAD

**Issue by ToruIwashita** [tyru/open-browser-github.vim#23]
いつも便利に使わせてもらっています。

Githubは `https://github.com/<OWNER>/<REPO>/pull/<branch>` のようにブランチ名を指定するとPull Requestのページにリダイレクトされるようです。（[参考](http://efcl.info/2015/02/01/github-open-pullrequest/)）

これを利用してブランチ名からPull Requestページを開けるようになると便利かなと思うのですが、そういった機能を追加してもらう事は可能でしょうか。。？

一応以下のような変更を加える事でサクッと実現はできたのですが、コードの全体感を把握できている訳ではないので適切なコードをどのように作ったら良いかは分かっていません。。ゼヒ機能追加をご検討頂けるとありがたいです。

```
diff --git a/autoload/openbrowser/github.vim b/autoload/openbrowser/github.vim
index e36da26..6b1695a 100644
--- a/autoload/openbrowser/github.vim
+++ b/autoload/openbrowser/github.vim
@@ -189,6 +189,8 @@ function! s:cmd_open_url(args, type)
     elseif a:type ==# s:TYPE_PULLREQ
         if number !=# ''
             let path = 'pull/' . number
+        elseif get(a:args, 0, '') !=# ''
+            let path = 'pull/' . a:args[0]
         else
             let path = 'pulls'
         endif
```

**Comment by tyru** [comment]
ご意見ありがとうございます。

@ToruIwashita さんのパッチだと `:OpenGithubPullReq branch_name` のような形式になるかと思いますが、これだと `:OpenGithubPullReq user/repo` の場合と区別が尽きません。
ブランチ名はスラッシュを含む事もできるため、スラッシュの有無ではブランチ名なのか `user/repo` なのかどうかは判断できません。

このような理由から、 `:OpenGithubPullReq #branch_name` のような書式であればいいと思うのですがどうでしょうか？
もし上記の仕様でよろしければ #25 のブランチに切り替えて頂いて、期待通りの動作になっているか確認してもらってもよろしいでしょうか？

**Comment by ToruIwashita** [comment]
> ブランチ名はスラッシュを含む事もできるため、スラッシュの有無ではブランチ名なのか user/repo なのかどうかは判断できません。
> このような理由から、 :OpenGithubPullReq #branch_name のような書式であればいいと思うのですがどうでしょうか？

なるほど、、確かに判断できないですね。
自分としては`#branch_name`という書式で全く問題ありません。

https://github.com/tyru/open-browser-github.vim/pull/25 にて期待通りの動作になっている事が確認できました。

ご対応ありがとうございます:bow:

**Comment by tyru** [comment]
@ToruIwashita 提案 & 確認ありがとうございました :bow:
