### ISSUE TITLE
Last update broke the plugin

### ISSUE THREAD

**Issue by stsewd** [tyru/open-browser-github.vim#26]
Hi, I'm using Neovim. When I updated the plugin this happens everytime I executed a `OpenGitHub*` command. Probably related to the recent changes on https://github.com/tyru/open-browser.vim/

```
Error detected while processing function openbrowser#github#file[3]..<SNR>368_call_with_temp_dir[12]..<SNR>368_cmd_file[1]..<SNR>368_parse_cmd_file_args[10]..<SNR>368_get_repos_relpath:         
line    3:                                                                                                                                                                                        
E117: Unknown function: s:git                                                                                                                                                                     
E15: Invalid expression: s:git('rev-parse', '--show-prefix')  
```

**Comment by stsewd** [comment]
Another trace

```
Error detected while processing /home/stsewd/.local/share/nvim/plugged/open-browser-github.vim/autoload/openbrowser/github.vim:                                                                   
line  398:                                                                                                                                                                                        
E121: Undefined variable: g:openbrowser_use_vimproc                                                                                                                                               
E15: Invalid expression: g:openbrowser_use_vimproc       && globpath(&rtp, 'autoload/vimproc.vim') !=# ''                                                                                         
Error detected while processing function openbrowser#github#file[3]..<SNR>222_call_with_temp_dir[12]..<SNR>222_cmd_file[1]..<SNR>222_parse_cmd_file_args[10]..<SNR>222_get_repos_relpath:         
line    3:                                                                                                                                                                                        
E117: Unknown function: s:git                                                                                                                                                                     
E15: Invalid expression: s:git('rev-parse', '--show-prefix')
```

**Comment by tyru** [comment]
I can not reproduce.
Do you use the latest versions of open-browser.vim, and open-browser-github.vim?

Or, maybe this is timing issue of loading order.
Where do you call `:OpenGithub*` command from?

**Comment by stsewd** [comment]
@tyru Yes, I am using the last two versions. I called it from a file inside a git repository like I used to. I'm not sure what happened, I tried using an older neovim version, and with just the two plugins but the problem persists. I'm going to research a little more. Thanks for your reply.

**Comment by tyru** [comment]
hmm, it seems open-browser.vim is not loaded when you run `:OpenGithub*` command (`g:openbrowser_use_vimproc` must be defined by open-browser.vim).
Can you execute `:OpenBrowser http://example.com/`, and does it open a browser?

**Comment by stsewd** [comment]
Yeah that works, now I have other clue. If I run first `:OpenBrowser` and then `OpenGitHub` everything works! If I run first `:OpenGibHub`, everything is broken (doesn't matter if I run `:OpenBrowser`)

**Comment by tyru** [comment]
ah, I see.
This is open-browser-github.vim issue.
Will fix soon (maybe in this week).

The previous version of open-browser.vim defines the variable when Vim starts up (plugin/openbrowser.vim).
But after v2.0.0 is released, now it is defined at runtime of `:OpenBrowser`.
so open-browser-github.vim must loads open-browser.vim if it has not loaded.

**Comment by stsewd** [comment]
@tyru great, thanks for your time!

**Comment by tyru** [comment]
Fixed in #27.
@stsewd Would you try the pull request's branch?

**Comment by stsewd** [comment]
@tyru The problem is fixed with that branch :smile:

**Comment by tyru** [comment]
@stsewd Thanks! Merged :)
